using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ExamenesVista

namespace SIMEPCI_Web.Controllers
{
    public class ExamenMedicoController : Controller
    {
        private static List<ExamenMedico> _examenes = new List<ExamenMedico>();
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
        private readonly IWebHostEnvironment _hostingEnvironment;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ExamenesVista

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
        public ExamenMedicoController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ExamenesVista
        public IActionResult Index()
        {
            return View(_examenes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(ExamenMedico examen)
        {
            if (ModelState.IsValid)
            {
                _examenes.Add(examen);
                return RedirectToAction(nameof(Index));
            }
            return View(_examenes);
        }
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================

        public IActionResult SubirImagen()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SubirImagen(IFormFile imagen)
        {
            if (imagen != null && imagen.Length > 0)
            {
                var fileName = Path.GetFileName(imagen.FileName);
                var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "uploads", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    imagen.CopyTo(fileStream);
                }
                return RedirectToAction(nameof(SubirImagen));
            }
            return View();
        }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ExamenesVista
    }

    public class ExamenMedico
    {
        public int Id { get; set; }
        public string Especialidad { get; set; }
        public string Procedimiento { get; set; }
        public DateTime Fecha { get; set; }
        public TimeSpan Hora { get; set; }
        public string Seccion { get; set; }
        public string Observaciones { get; set; }
    }
}